// BUDGET
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const LOAD_BUDGETS = 'LOAD_BUDGETS';
export const LOAD_BUDGETS_SUCCESS = 'LOAD_BUDGETS_SUCCESS';
export const SET_CURRENT_BUDGET = 'SET_CURRENT_BUDGET';

// USER
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';

// MODAL
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
