/** USER */
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';


/** BUDGET */
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const LOAD_BUDGETS_SUCCESS = 'LOAD_BUDGETS_SUCCESS';
export const SET_CURRENT_BUDGET = 'SET_CURRENT_BUDGET';
export const DELETE_BUDGET_SUCCESS = 'DELETE_BUDGET_SUCCESS';

/** ACCOUNT */
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';


/** MASTER CATEGORY */
export const ADD_MASTER_CATEGORY_SUCCESS = 'ADD_MASTER_CATEGORY_SUCCESS';
export const UPDATE_MASTER_CATEGORY_SUCCESS = 'UPDATE_MASTER_CATEGORY_SUCCESS';


/** CATEGORY */
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';


/** TIMESPAN */
export const SET_CURRENT_TIMESPAN = 'SET_CURRENT_TIMESPAN'; 


/** CATEGORY BUDGET */
export const SAVE_CATEGORY_BUDGET_SUCCESS = 'SAVE_CATEGORY_BUDGET_SUCCESS';
export const LOAD_CATEGORY_BUDGETS_SUCCESS = 'LOAD_CATEGORY_BUDGETS_SUCCESS';

/** TRANSACTION */
export const LOAD_TRANSACTIONS_SUCCESS = 'LOAD_TRANSACTIONS_SUCCESS';
export const CREATE_TRANSACTION= 'CREATE_TRANSACTION';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const UPDATE_TRANSACTION_SUCCESS = 'UPDATE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_SUCCESS = 'DELETE_TRANSACTION_SUCCESS';
export const DELETE_TRANSACTION_FAILURE = 'DELETE_TRANSACTION_FAILURE';

/** PAYEES */
export const LOAD_PAYEES_SUCCESS = 'LOAD_PAYEES_SUCCESS';
export const CREATE_PAYEE_SUCCESS = 'CREATE_PAYEE_SUCCESS';

/** MODAL */
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
