/** USER */
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
export const GET_USER_DATA = 'GET_USER_DATA';


/** BUDGET */
export const CREATE_BUDGET = 'CREATE_BUDGET';
export const LOAD_BUDGETS = 'LOAD_BUDGETS';
export const LOAD_BUDGETS_SUCCESS = 'LOAD_BUDGETS_SUCCESS';
export const SET_CURRENT_BUDGET = 'SET_CURRENT_BUDGET';

/** ACCOUNT */
export const ADD_ACCOUNT_SUCCESS = 'ADD_ACCOUNT_SUCCESS';


/** MASTER CATEGORY */
export const ADD_MASTER_CATEGORY_SUCCESS = 'ADD_MASTER_CATEGORY_SUCCESS';


/** CATEGORY */
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';


/** MODAL */
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
